# The Numpy array object

# NumPy Arrays

In [ ]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [ ]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [ ]:
#print dimensions

a.ndim

1

In [3]:
#shape
import numpy as np
a = np.array([0, 1, 2, 3])


a.shape

(4,)

In [ ]:
len(a)

4

In [ ]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
len(b) #returns the size of the first dimention

2

** 1.2  Functions for creating arrays**

In [4]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [6]:
#using linspace

a = np.linspace(0, 1, 9) #start, end, number of points

a

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [ ]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [8]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4)

a

array([0.53083789, 0.14578993, 0.94466869, 0.77399505])

In [ ]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 1.14127245,  1.70779562, -1.05629155, -1.1072947 ])

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [ ]:
a = np.arange(10)

a.dtype

dtype('int64')

In [ ]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [ ]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [ ]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [ ]:
a = np.arange(10)
print(a)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

[0 1 2 3 4 5 6 7 8 9]
5


In [13]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1,2,3])
print(a)
print(a[1,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
2


In [14]:
a[2, 1] = 5 #assigning value
a[1,0]=9
a

array([[1, 0, 0],
       [9, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [ ]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [34]:
#we can also combine assignment and slicing:

a = np.arange(10)
print(a)
a[5:] = 10
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [35]:
b = np.arange(5)
print(b)
print(b[::-1])
a[5:] = b[::-1]  #assigning

a

[0 1 2 3 4]
[4 3 2 1 0]


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [17]:
a = np.random.randint(0, 20, 15)
a

array([10,  3,  5,  9, 17, 15,  7,  5, 17,  3, 10,  7,  4,  6, 12])

In [18]:
mask = (a % 2 == 0)

In [19]:
extract_from_a = a[mask]

extract_from_a

array([10, 10,  4,  6, 12])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [ ]:
a[mask] = -1
a

array([-1, -1, -1, 19, -1, 11,  7, -1, -1, 11,  7,  7, -1,  3, -1])

**Indexing with an array of integers**

In [27]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [30]:
# New values can be assigned

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])